import type { MatchScorecardView } from "./types";

/** Edgware U9 M4 — Hayes vs Edgware (31 May 2026). Static demo for UI development. */
export const edgwareM4DemoScorecard: MatchScorecardView = {
  matchTitle: "Hayes vs Edgware CC",
  venue: "The Pavilion, Hayes (Away)",
  date: "31 May 2026",
  status: "COMPLETED",
  resultBanner: {
    text: "Hayes won by 51 runs",
    subtext: "20 overs · U9 Softball",
    variant: "loss",
  },
  toss: {
    winnerName: "Hayes",
    electedTo: "bat",
  },
  rulesNote:
    "Base 200 + bat runs − 5 per wicket. Net runs = bat runs − (5 × wickets lost).",
  innings: [
    {
      teamName: "Hayes",
      inningsLabel: "Hayes — Batting 1st Innings",
      totalRuns: 281,
      wickets: 9,
      overs: 20,
      batRuns: 81,
      netRuns: 36,
      startingScore: 200,
      batRunsFromPlay: 81,
      extras: { total: 0, wides: 0, noBalls: 0, byes: 0, legByes: 0 },
      batters: [
        { playerId: "1", name: "Sahib", dismissal: "wkt ×2", runs: 0, balls: 0, fours: 0, sixes: 0, netRuns: -10, wicketsLost: 2, isNotOut: false },
        { playerId: "2", name: "Ekamvir", dismissal: "wkt ×2", runs: 0, balls: 0, fours: 0, sixes: 0, netRuns: -10, wicketsLost: 2, isNotOut: false },
        { playerId: "3", name: "Gurfateh", dismissal: "not out", runs: 16, balls: 0, fours: 2, sixes: 0, netRuns: 26, wicketsLost: 0, isNotOut: true },
        { playerId: "4", name: "Elijah", dismissal: "run out ×1", runs: 3, balls: 0, fours: 0, sixes: 0, netRuns: 5, wicketsLost: 1, isNotOut: false },
        { playerId: "5", name: "Rudransh", dismissal: "c Shyam b Kaiyan (Ov 12)", runs: 5, balls: 0, fours: 1, sixes: 0, netRuns: 7, wicketsLost: 0, isNotOut: false },
        { playerId: "6", name: "Arnav", dismissal: "wkt ×2", runs: 11, balls: 0, fours: 4, sixes: 0, netRuns: 11, wicketsLost: 0, isNotOut: false },
        { playerId: "7", name: "Harshan", dismissal: "wkt ×1", runs: 9, balls: 0, fours: 1, sixes: 0, netRuns: 15, wicketsLost: 0, isNotOut: false },
        { playerId: "8", name: "Sehaj", dismissal: "not out", runs: 4, balls: 0, fours: 0, sixes: 0, netRuns: 8, wicketsLost: 0, isNotOut: true },
        { playerId: "9", name: "Eknoor", dismissal: "not out", runs: 2, balls: 0, fours: 0, sixes: 0, netRuns: 2, wicketsLost: 0, isNotOut: true },
        { playerId: "10", name: "Gurman", dismissal: "wkt ×1", runs: 7, balls: 0, fours: 0, sixes: 0, netRuns: 7, wicketsLost: 0, isNotOut: false },
      ],
      bowlers: [
        { playerId: "b1", name: "Aanya", overs: 2, maidens: 0, runs: 7, wickets: 0, wides: 0, noBalls: 0, dots: 6, economy: 3.5 },
        { playerId: "b2", name: "Qaim", overs: 2, maidens: 0, runs: 7, wickets: 1, wides: 0, noBalls: 0, dots: 6, economy: 3.5 },
        { playerId: "b3", name: "Krish", overs: 2, maidens: 0, runs: 7, wickets: 1, wides: 0, noBalls: 0, dots: 7, economy: 3.5 },
        { playerId: "b4", name: "Kaiyan", overs: 2, maidens: 0, runs: 8, wickets: 1, wides: 2, noBalls: 0, dots: 6, economy: 4.0 },
        { playerId: "b5", name: "Drish", overs: 2, maidens: 0, runs: 10, wickets: 0, wides: 0, noBalls: 1, dots: 3, economy: 5.0 },
        { playerId: "b6", name: "Taran", overs: 2, maidens: 0, runs: 12, wickets: 1, wides: 1, noBalls: 0, dots: 3, economy: 6.0 },
        { playerId: "b7", name: "Avyaan", overs: 2, maidens: 0, runs: 12, wickets: 1, wides: 3, noBalls: 1, dots: 4, economy: 6.0 },
        { playerId: "b8", name: "Ariyan", overs: 2, maidens: 0, runs: 15, wickets: 1, wides: 0, noBalls: 0, dots: 5, economy: 7.5 },
        { playerId: "b9", name: "Veer", overs: 2, maidens: 0, runs: 14, wickets: 0, wides: 3, noBalls: 0, dots: 2, economy: 7.0 },
        { playerId: "b10", name: "Shyam", overs: 2, maidens: 0, runs: 17, wickets: 1, wides: 1, noBalls: 1, dots: 5, economy: 8.5 },
      ],
      fallOfWickets: [],
      partnerships: [
        { label: "P1", batter1: "Sahib", batter2: "Ekamvir", runs: 0, balls: 0, fours: 0, sixes: 0, wickets: 2, netRuns: -5 },
        { label: "P2", batter1: "Gurfateh", batter2: "Elijah", runs: 19, balls: 0, fours: 0, sixes: 0, wickets: 1, netRuns: 31 },
        { label: "P3", batter1: "Rudransh", batter2: "Arnav", runs: 16, balls: 0, fours: 0, sixes: 0, wickets: 0, netRuns: 18 },
        { label: "P4", batter1: "Harshan", batter2: "Sehaj", runs: 13, balls: 0, fours: 0, sixes: 0, wickets: 0, netRuns: 23 },
        { label: "P5", batter1: "Eknoor", batter2: "Gurman", runs: 9, balls: 0, fours: 0, sixes: 0, wickets: 0, netRuns: 9 },
      ],
      fielding: [
        { fielderName: "Shyam", catches: 1, runOuts: 0, details: ["c Shyam b Kaiyan — Ov 12"] },
        { fielderName: "Taran", catches: 1, runOuts: 1, details: ["c Taran b Avyaan — Ov 16", "run out (Taran) — Ov 7"] },
        { fielderName: "Krish", catches: 0, runOuts: 1, details: ["run out (Krish) — Ov 4"] },
      ],
    },
    {
      teamName: "Edgware CC",
      inningsLabel: "Edgware CC — Batting 2nd Innings",
      totalRuns: 230,
      wickets: 15,
      overs: 20,
      batRuns: 30,
      netRuns: -45,
      startingScore: 200,
      batRunsFromPlay: 30,
      extras: { total: 0, wides: 0, noBalls: 0, byes: 0, legByes: 0 },
      batters: [
        { playerId: "e1", name: "Qaim", dismissal: "wkt ×2", runs: 4, balls: 0, fours: 0, sixes: 0, netRuns: -6, wicketsLost: 2, isNotOut: false },
        { playerId: "e2", name: "Krish", dismissal: "wkt ×4", runs: 6, balls: 0, fours: 0, sixes: 0, netRuns: -14, wicketsLost: 4, isNotOut: false },
        { playerId: "e3", name: "Drish", dismissal: "not out", runs: 5, balls: 0, fours: 0, sixes: 0, netRuns: 5, wicketsLost: 0, isNotOut: true },
        { playerId: "e4", name: "Shyam", dismissal: "wkt ×3", runs: 2, balls: 0, fours: 0, sixes: 0, netRuns: -13, wicketsLost: 3, isNotOut: false },
        { playerId: "e5", name: "Aanya", dismissal: "wkt ×1", runs: 1, balls: 0, fours: 0, sixes: 0, netRuns: -4, wicketsLost: 1, isNotOut: false },
        { playerId: "e6", name: "Veer", dismissal: "not out", runs: 8, balls: 0, fours: 0, sixes: 0, netRuns: 8, wicketsLost: 0, isNotOut: true },
        { playerId: "e7", name: "Avyaan", dismissal: "wkt ×1", runs: 3, balls: 0, fours: 0, sixes: 0, netRuns: -2, wicketsLost: 1, isNotOut: false },
        { playerId: "e8", name: "Kaiyan", dismissal: "wkt ×1", runs: 4, balls: 0, fours: 0, sixes: 0, netRuns: -1, wicketsLost: 1, isNotOut: false },
        { playerId: "e9", name: "Taran", dismissal: "wkt ×2", runs: 7, balls: 0, fours: 1, sixes: 0, netRuns: -3, wicketsLost: 2, isNotOut: false },
        { playerId: "e10", name: "Ariyan", dismissal: "wkt ×3", runs: 7, balls: 0, fours: 0, sixes: 0, netRuns: -8, wicketsLost: 3, isNotOut: false },
      ],
      bowlers: [
        { playerId: "h1", name: "Harshan", overs: 2, maidens: 0, runs: 3, wickets: 1, wides: 1, noBalls: 0, dots: 8, economy: 1.5 },
        { playerId: "h2", name: "Sehaj", overs: 2, maidens: 0, runs: 4, wickets: 0, wides: 2, noBalls: 1, dots: 6, economy: 2.0 },
        { playerId: "h3", name: "Gurfateh", overs: 2, maidens: 0, runs: 5, wickets: 1, wides: 1, noBalls: 0, dots: 7, economy: 2.5 },
        { playerId: "h4", name: "Sahib", overs: 2, maidens: 0, runs: 7, wickets: 1, wides: 2, noBalls: 0, dots: 5, economy: 3.5 },
        { playerId: "h5", name: "Ekamvir", overs: 2, maidens: 0, runs: 7, wickets: 3, wides: 2, noBalls: 0, dots: 5, economy: 3.5 },
        { playerId: "h6", name: "Arnav", overs: 2, maidens: 0, runs: 7, wickets: 1, wides: 3, noBalls: 0, dots: 5, economy: 3.5 },
        { playerId: "h7", name: "Eknoor", overs: 2, maidens: 0, runs: 7, wickets: 4, wides: 2, noBalls: 1, dots: 8, economy: 3.5 },
        { playerId: "h8", name: "Rudransh", overs: 2, maidens: 0, runs: 8, wickets: 0, wides: 3, noBalls: 0, dots: 5, economy: 4.0 },
        { playerId: "h9", name: "Elijah", overs: 2, maidens: 0, runs: 9, wickets: 0, wides: 7, noBalls: 0, dots: 2, economy: 4.5 },
        { playerId: "h10", name: "Gurman", overs: 2, maidens: 0, runs: 11, wickets: 1, wides: 1, noBalls: 0, dots: 4, economy: 5.5 },
      ],
      fallOfWickets: [],
      partnerships: [
        { label: "P1", batter1: "Qaim", batter2: "Krish", runs: 10, balls: 0, fours: 0, sixes: 0, wickets: 2, netRuns: -20 },
        { label: "P2", batter1: "Drish", batter2: "Shyam", runs: 7, balls: 0, fours: 0, sixes: 0, wickets: 1, netRuns: -8 },
        { label: "P3", batter1: "Aanya", batter2: "Veer", runs: 9, balls: 0, fours: 0, sixes: 0, wickets: 0, netRuns: 4 },
        { label: "P4", batter1: "Avyaan", batter2: "Kaiyan", runs: 7, balls: 0, fours: 0, sixes: 0, wickets: 0, netRuns: -3 },
        { label: "P5", batter1: "Taran", batter2: "Ariyan", runs: 14, balls: 0, fours: 0, sixes: 0, wickets: 0, netRuns: -4 },
      ],
      fielding: [],
    },
  ],
};
